<?php

namespace Database\Seeders;

use App\Models\Address;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ADDRESS::create(['id' => 1, 'street' => 'Bismarckstraße. 68', 'postal_code' => '12157', 'city' => 'Berlin', 'district' => 'Steglitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 2, 'street' => 'Groß-Ziethener Chaussee  61', 'postal_code' => '12355', 'city' => 'Berlin ', 'district' => 'Rudow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 3, 'street' => 'Sophie-Charlotten-Str. 41', 'postal_code' => '14059', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 4, 'street' => 'Sömmeringstr 24', 'postal_code' => '10589', 'city' => 'Berlin', 'district' => 'Charlottenburg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 5, 'street' => 'Bayernring 15', 'postal_code' => '12101', 'city' => 'Berlin', 'district' => 'Tempelhof', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 6, 'street' => 'Havemannstr 12a', 'postal_code' => '12689', 'city' => 'Berlin ', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 7, 'street' => 'Herrmann Hesse Str 14', 'postal_code' => '13156', 'city' => 'Berlin', 'district' => 'Niederschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 8, 'street' => 'Karl-Marx-Str. 60', 'postal_code' => '14532', 'city' => 'Kleinmachnow', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 9, 'street' => 'Schönhauser Allee 36', 'postal_code' => '10435', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 10, 'street' => 'Am Ostbahnhof 9', 'postal_code' => '10243', 'city' => 'Berlin', 'district' => 'Friedrichshain ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 11, 'street' => 'Johannes-Keppler-Platz 5', 'postal_code' => '14480', 'city' => 'Potsdam', 'district' => 'Am Stern', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 12, 'street' => 'Goerzallee 58', 'postal_code' => '12207', 'city' => 'Berlin', 'district' => 'Lichterfelde ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 13, 'street' => 'Konrad-Wolf-Str 24', 'postal_code' => '13055', 'city' => 'Berlin ', 'district' => 'Alt-Hohenschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 14, 'street' => 'Gorkistr 9', 'postal_code' => '13507', 'city' => 'Berlin', 'district' => 'Tegel', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 15, 'street' => 'Uhlandstr. 30', 'postal_code' => '10719', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 16, 'street' => 'Kurfürstendamm 146', 'postal_code' => '10709', 'city' => 'Berlin', 'district' => 'Charlottenburg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 17, 'street' => 'Bernhard-Bästlein-Str 1', 'postal_code' => '10367', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 18, 'street' => 'Großbeerenstr. 62', 'postal_code' => '12107', 'city' => 'Berlin', 'district' => 'Mariendorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 19, 'street' => 'Friedrichstr 111', 'postal_code' => '10117', 'city' => 'Berlin ', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 20, 'street' => 'Hleidestr 41', 'postal_code' => '10557', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 21, 'street' => 'Schivelbeiner str. 38', 'postal_code' => '10439', 'city' => 'Berlin ', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 22, 'street' => 'Walther Schreiber Platz 1', 'postal_code' => '12161', 'city' => 'Berlin', 'district' => 'Friedenau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 23, 'street' => 'Wollankstr. 16', 'postal_code' => '13187', 'city' => 'Berlin', 'district' => 'Pankow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 24, 'street' => 'Am Borsigturm 2', 'postal_code' => '13507', 'city' => 'Berlin ', 'district' => 'Reinickendorf ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 25, 'street' => 'Breisgauer Str. 1', 'postal_code' => '14129', 'city' => 'Berlin', 'district' => 'Zehlendorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 26, 'street' => 'Rollbergstr. 59', 'postal_code' => '12053', 'city' => 'Berlin ', 'district' => 'Neukölln ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 27, 'street' => 'Turmstr 48', 'postal_code' => '10551', 'city' => 'Berlin ', 'district' => 'Wedding', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 28, 'street' => 'Yorckstr. 48', 'postal_code' => '10965', 'city' => 'Berlin', 'district' => 'Kreuzberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 29, 'street' => 'Kaiserin Augusta Str 55', 'postal_code' => '12103', 'city' => 'Berlin', 'district' => 'Tempelhof ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 30, 'street' => 'Bismarckstraße 91', 'postal_code' => '10625', 'city' => 'Berlin ', 'district' => 'Charlottenburg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 31, 'street' => 'Wundtstr 26', 'postal_code' => '14059', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 32, 'street' => 'Schönhauser Allee 130', 'postal_code' => '10437', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 33, 'street' => 'Grellstr. 75', 'postal_code' => '10409', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 34, 'street' => 'Am Tierpark  68', 'postal_code' => '10319', 'city' => 'Berlin ', 'district' => 'Friedrichsfelde ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 35, 'street' => 'Alfred Jung Str 12', 'postal_code' => '10369', 'city' => 'Berlin ', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 36, 'street' => 'Obofeldstr 138', 'postal_code' => '12683', 'city' => 'Berlin', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 37, 'street' => 'Genslerstr 34', 'postal_code' => '13055', 'city' => 'Berlin ', 'district' => 'Hohenschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 38, 'street' => 'Ribnitzer Str 26', 'postal_code' => '13051', 'city' => 'Berlin', 'district' => 'Hohenschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 39, 'street' => 'Prerower Platz 1', 'postal_code' => '13051', 'city' => 'Berlin', 'district' => 'Hohenschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 40, 'street' => 'Landsberger Allee 68D', 'postal_code' => '10249', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 41, 'street' => 'Frankfurter Allee 144', 'postal_code' => '10365', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 42, 'street' => 'Helene Weigel Platz 1', 'postal_code' => '12681', 'city' => 'Berlin', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 43, 'street' => 'Alfred kowalke Str 2', 'postal_code' => '10315', 'city' => 'Berlin', 'district' => 'Friedrichsfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 44, 'street' => 'Germaniastr 12', 'postal_code' => '12099', 'city' => 'Berlin', 'district' => 'Tempelhof', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 45, 'street' => 'Theodor-Heuss-Platz 6', 'postal_code' => '14052', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 46, 'street' => 'Clayallee 336', 'postal_code' => '14169', 'city' => 'Berlin ', 'district' => 'Zehlendorf ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 47, 'street' => 'Wrangelstr 53', 'postal_code' => '10997', 'city' => 'Berlin ', 'district' => 'Kreuzberg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 48, 'street' => 'Herrmannstr 158', 'postal_code' => '12051', 'city' => 'Berlin ', 'district' => 'Neukölln ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 49, 'street' => 'Europaplatz 1', 'postal_code' => '10557', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 50, 'street' => 'Nonnendammallee 120', 'postal_code' => '13629', 'city' => 'Berlin ', 'district' => 'Siemensstadt', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 51, 'street' => 'Hauptstr. 141', 'postal_code' => '10551', 'city' => 'Berlin ', 'district' => 'Schöneberg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 52, 'street' => 'Töpchiner Weg 189', 'postal_code' => '12309', 'city' => 'Berlin ', 'district' => 'Lichtenrade', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 53, 'street' => 'Angermünder Allee 55', 'postal_code' => '14055', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 54, 'street' => 'Kurfürstendamm 142', 'postal_code' => '10709', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 55, 'street' => 'Konstanzer Str 53', 'postal_code' => '10707', 'city' => 'Belin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 56, 'street' => 'Südwestkorso 36', 'postal_code' => '14197', 'city' => 'Berlin', 'district' => 'Wilmersdorf ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 57, 'street' => 'Königin Luise Str. 37', 'postal_code' => '14195', 'city' => 'Berlin ', 'district' => 'Dahlem ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 58, 'street' => 'Hildburghauser Str. 29', 'postal_code' => '12279', 'city' => 'Berlin', 'district' => 'Lichterfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 59, 'street' => 'Hackescher Markt 4', 'postal_code' => '10178', 'city' => 'Berlin ', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 60, 'street' => 'Bahnhofstr  33', 'postal_code' => '12555', 'city' => 'Berlin', 'district' => 'Köpenick', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 61, 'street' => 'Zum großen Zernsee 2', 'postal_code' => '14542', 'city' => 'Bliesendorf', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 62, 'street' => 'Nedlitzer Str. 19c', 'postal_code' => '14469', 'city' => 'Potsdam', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 63, 'street' => 'Invalidenstr. 158', 'postal_code' => '10115', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 64, 'street' => 'Chausseestr 118', 'postal_code' => '10115', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 65, 'street' => 'Schönhauser Allee 10', 'postal_code' => '10119', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 66, 'street' => 'Weitlingstr. 59', 'postal_code' => '10317', 'city' => 'Berlin ', 'district' => 'Friedrichsfelde ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 67, 'street' => 'Rheinstraße. 30', 'postal_code' => '12161', 'city' => 'Berlin', 'district' => 'Friedenau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 68, 'street' => 'Bruno Taut Str 1', 'postal_code' => '12524', 'city' => 'Berlin', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 69, 'street' => 'Pablo Nerunda Str 2', 'postal_code' => '12555', 'city' => 'Brolin', 'district' => 'Köpenick, ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 70, 'street' => 'Mehrower Allee 20', 'postal_code' => '12687', 'city' => 'Berlin', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 71, 'street' => 'Luisenstr 7', 'postal_code' => '15831', 'city' => 'Mahlow', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 72, 'street' => 'Friedrichst 60', 'postal_code' => '10117', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 73, 'street' => 'Pasteurstr 17-19', 'postal_code' => '10409', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 74, 'street' => 'Sterndamm 140', 'postal_code' => '12487', 'city' => 'Berlin', 'district' => 'Johannisthal', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 75, 'street' => 'Streitstr  59', 'postal_code' => '13587', 'city' => 'Berl7n', 'district' => 'Spandau ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 76, 'street' => 'Kiehlufer 79', 'postal_code' => '12059', 'city' => 'Berlin', 'district' => 'Neukölln ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 77, 'street' => 'Celsiusstr 66', 'postal_code' => '12207', 'city' => 'Berlin ', 'district' => 'Lichterfelde ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 78, 'street' => 'Liebewowzeile 29', 'postal_code' => '12167', 'city' => 'Berlin', 'district' => 'Lankwitz ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 79, 'street' => 'Bottroper weg 18', 'postal_code' => '13507', 'city' => 'Berlin ', 'district' => 'Tegel ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 80, 'street' => 'Hirtsiferzeile 42', 'postal_code' => '12351', 'city' => 'Berlin ', 'district' => 'Rudow ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 81, 'street' => 'Drakestr. 33', 'postal_code' => '12205', 'city' => 'Berlin ', 'district' => 'Lichterfelde ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 82, 'street' => 'Gersdorfstr 40', 'postal_code' => '12105', 'city' => 'Berlin', 'district' => 'Mariendoof', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 83, 'street' => 'Galileistr 16', 'postal_code' => '14480', 'city' => 'Potsdam', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 84, 'street' => 'Fritschestr 45-46', 'postal_code' => '10627', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 85, 'street' => 'Liselotte Berger Platz 4', 'postal_code' => '12355', 'city' => 'Berlin ', 'district' => 'Rudow ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 86, 'street' => 'Kaiser Wilhelm Str. 38', 'postal_code' => '12247', 'city' => 'Berlin', 'district' => 'Lankwitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 87, 'street' => 'Bahnhofstr. 22', 'postal_code' => '14823', 'city' => 'Niemegk', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 88, 'street' => 'Spandauer Str 160b', 'postal_code' => '14612', 'city' => 'Falkensee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 89, 'street' => 'Adamstr 6', 'postal_code' => '13595', 'city' => 'Berlin ', 'district' => 'Spandau ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 90, 'street' => 'Bötzowstr. 23', 'postal_code' => '10407', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 91, 'street' => 'Hildburghauser Str 196', 'postal_code' => '12209', 'city' => 'Berlin', 'district' => 'Lichterfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 92, 'street' => 'Im Spektefeld  32', 'postal_code' => '13589', 'city' => 'Berlin', 'district' => 'Spandau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 93, 'street' => 'Buckower Damm 106', 'postal_code' => '12349', 'city' => 'Berlin', 'district' => 'Buckon', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 94, 'street' => 'Birkbuschstraße 76', 'postal_code' => '12167', 'city' => 'Berlin', 'district' => 'Steglitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 95, 'street' => 'Dessauer Str. 64', 'postal_code' => '12249', 'city' => 'Berlin', 'district' => 'Lankwitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 96, 'street' => 'Haselhorster Damm 27', 'postal_code' => '13599', 'city' => 'Berlin', 'district' => 'Spandau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 97, 'street' => 'Am Nuthefließ 4', 'postal_code' => '14943', 'city' => 'Luckenwalde', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 98, 'street' => 'Am Markt  6', 'postal_code' => '15517', 'city' => '', 'district' => 'Fürstenwalde/Spee', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 99, 'street' => 'Quarzweg 85', 'postal_code' => '12349', 'city' => 'Berlin', 'district' => 'Buckow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 100, 'street' => 'Von-Stechow-Str 10', 'postal_code' => '14476', 'city' => 'Fahrland', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 101, 'street' => 'Wrangelstr 75', 'postal_code' => '10997', 'city' => 'Berlin', 'district' => 'Kreuzberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 102, 'street' => 'Köpenicker str. 192', 'postal_code' => '12683', 'city' => 'Berlin', 'district' => 'Diesdorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 103, 'street' => 'Volkradstr. 32', 'postal_code' => '10319', 'city' => 'Berlin', 'district' => 'Friedrichsfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 104, 'street' => 'Emmentaler Str. 122', 'postal_code' => '13409', 'city' => 'Berlin', 'district' => 'Reinickendorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 105, 'street' => 'Otto-Suhr-Allee 80', 'postal_code' => '10585', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 106, 'street' => 'Turmstr. 60', 'postal_code' => '10551', 'city' => 'Berlin', 'district' => 'Tiergarten', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 107, 'street' => 'Malteserstr. 128', 'postal_code' => '12249', 'city' => 'Lankwitz', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 108, 'street' => 'Schnellerstr. 74', 'postal_code' => '12439', 'city' => 'Berlin', 'district' => 'Niederschöneweide', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 109, 'street' => 'Alte Potsdamer Str. 1', 'postal_code' => '10785', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 110, 'street' => 'Kiefholzstr. 50', 'postal_code' => '12435', 'city' => 'Berlin', 'district' => 'Alt-Treptow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 111, 'street' => 'Anton Saefkow Platz  10', 'postal_code' => '10369', 'city' => 'Berlin', 'district' => 'Lichtenberg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 112, 'street' => 'Neumannstr 13', 'postal_code' => '13189', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 113, 'street' => 'Friedrichistr 67', 'postal_code' => '10117', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 114, 'street' => 'Schlangebader Str. 25', 'postal_code' => '14197', 'city' => 'Berlin', 'district' => 'Friedenau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 115, 'street' => 'In der Feldmark 3', 'postal_code' => '14476', 'city' => 'Golm', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 116, 'street' => 'Wuhlestr. 31', 'postal_code' => '12683', 'city' => 'Berlin', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 117, 'street' => 'Bahnhofstr 72', 'postal_code' => '14612', 'city' => 'Falkensee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 118, 'street' => 'Adlergestell 744', 'postal_code' => '12527', 'city' => 'Berlin', 'district' => 'Bohnsdorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 119, 'street' => 'Tempelhofer Weg 9', 'postal_code' => '12437', 'city' => 'Berlin ', 'district' => 'Neukölln', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 120, 'street' => 'Rustweg 1', 'postal_code' => '13587', 'city' => 'Berlin', 'district' => 'Spandau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 121, 'street' => 'Schilfhof 22', 'postal_code' => '14482', 'city' => 'Potsdam', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 122, 'street' => 'Trebuser Str. 1', 'postal_code' => '15517', 'city' => 'Fürstenwalde/Spee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 123, 'street' => 'Zeperniker Str. 10', 'postal_code' => '13125', 'city' => 'Berlin ', 'district' => 'Buch', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 124, 'street' => 'Rummelsburger Str 16', 'postal_code' => '12459', 'city' => 'Berlin', 'district' => 'Oberschöneweide', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 125, 'street' => 'Haslacher str 2', 'postal_code' => '14656', 'city' => 'Brieselang', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 126, 'street' => 'Ostseestr 23', 'postal_code' => '10409', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 127, 'street' => 'Ernststr. 7', 'postal_code' => '13509', 'city' => 'Berlin', 'district' => 'Tegel', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 128, 'street' => 'Köthener Str 1', 'postal_code' => '12689', 'city' => 'Berlin', 'district' => 'Marzahn', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 129, 'street' => 'Bahnhofstr 23', 'postal_code' => '12555', 'city' => 'Berlin', 'district' => 'Köpenick', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 130, 'street' => 'Ruhlsdorfer Str. 87', 'postal_code' => '14513', 'city' => 'Teltow', 'district' => '', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 131, 'street' => 'Schönfließer Str. 1a', 'postal_code' => '16552', 'city' => 'Schildow', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 132, 'street' => 'Am Mühlengraben 4', 'postal_code' => '14959', 'city' => 'Trebbin', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 133, 'street' => 'Potsdamer Str. 177', 'postal_code' => '14469', 'city' => 'Potsdam', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 134, 'street' => 'Hauffstr. 34', 'postal_code' => '14584', 'city' => 'Schwielosee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 135, 'street' => 'Am Pfarracker 1 1', 'postal_code' => '12529', 'city' => 'Schönefeld', 'district' => 'Großziethen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 136, 'street' => 'Ladiusstr. 26', 'postal_code' => '14165', 'city' => 'Berlin', 'district' => 'Zehlendorf ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 137, 'street' => 'Hauptstr 45', 'postal_code' => '15741', 'city' => 'Bestensee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 138, 'street' => 'Karl-Marx-Str. 92', 'postal_code' => '12043', 'city' => 'Berlin', 'district' => 'Neukölln', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 139, 'street' => 'Auerbacher Str. 12', 'postal_code' => '14193', 'city' => 'Berlin', 'district' => 'Grunewald', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 140, 'street' => 'Friedrichstraße. 100', 'postal_code' => '10117', 'city' => 'Berlin ', 'district' => 'Mitte ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 141, 'street' => 'Auerbacher Str. 12', 'postal_code' => '14193', 'city' => 'Berlin', 'district' => 'Grunewald', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 142, 'street' => 'Dolgenseestr 8', 'postal_code' => '10319', 'city' => 'Berlin ', 'district' => 'Fridrichsfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 143, 'street' => 'Alt-Rudow 64', 'postal_code' => '12355', 'city' => 'Berlin', 'district' => 'Rudow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 144, 'street' => 'Gotlindestr 4Da', 'postal_code' => '10365', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 145, 'street' => 'Thiemannstr 9', 'postal_code' => '12053', 'city' => 'Berlin ', 'district' => 'Neukölln', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 146, 'street' => 'Eldenaer Str. 42', 'postal_code' => '10247', 'city' => 'Berlin', 'district' => 'Friedrichshain', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 147, 'street' => 'Eldenaer Str 43', 'postal_code' => '10247', 'city' => 'Berlin', 'district' => 'Friedrichshain', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 148, 'street' => 'Hackelstr. 30', 'postal_code' => '14473', 'city' => 'Potsdam ', 'district' => 'Westend', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 149, 'street' => 'Rousseauallee 22', 'postal_code' => '14974', 'city' => 'Ludwigsfelde', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 150, 'street' => 'Rheinstr 14', 'postal_code' => '14159', 'city' => 'Berlin', 'district' => 'Friedenau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 151, 'street' => 'Malteserstr. 128', 'postal_code' => '12249', 'city' => 'Lankwitz', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 152, 'street' => 'Revaler Straße 33', 'postal_code' => '10245', 'city' => 'Berlin', 'district' => 'Friedrichshain', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 153, 'street' => 'Mullerst. 14', 'postal_code' => '13353', 'city' => 'Berlin', 'district' => 'Wedding', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 154, 'street' => 'Fritz Lang Str 3', 'postal_code' => '12627', 'city' => 'Berlin', 'district' => 'Hellersdorf', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 155, 'street' => 'John Schehr Str. 20', 'postal_code' => '10907', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 156, 'street' => 'Straße der Einheit 4a', 'postal_code' => '15938', 'city' => 'Golßen', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 157, 'street' => 'Daumstr 90', 'postal_code' => '13599', 'city' => 'Berlin', 'district' => 'Haselhorst', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 158, 'street' => 'Anni van Gottberg Str 8', 'postal_code' => '14480', 'city' => 'Potsdam ', 'district' => 'Kirchsteigfeld', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 159, 'street' => 'Sterndamm 31 31', 'postal_code' => '12487', 'city' => 'Berlin', 'district' => 'Johannisthal', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 160, 'street' => 'Wildhüterweg 42', 'postal_code' => '12353', 'city' => 'Berlin', 'district' => 'Buckow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 161, 'street' => 'Otto-Suhr-Allee 141', 'postal_code' => '10585', 'city' => 'Berlin ', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 162, 'street' => 'Vincent van Gogh Str. 18', 'postal_code' => '13057', 'city' => 'Berlin', 'district' => 'Hohenschönhausen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 163, 'street' => 'Oberspreestr. 145', 'postal_code' => '12555', 'city' => 'Berlin', 'district' => 'Köpenik', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 164, 'street' => 'Pappelallee 47', 'postal_code' => '10437', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 165, 'street' => 'Landsberger Allee 68', 'postal_code' => '10249', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 166, 'street' => 'Landsberger Allee 117', 'postal_code' => '10407', 'city' => 'Berlin', 'district' => 'Friedrichshain ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 167, 'street' => 'Bildburghausen Str. 29', 'postal_code' => '12279', 'city' => 'Berlin', 'district' => 'Lichterfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 168, 'street' => 'Bartningallee 3', 'postal_code' => '10557', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 169, 'street' => 'Sacrower Landstr  1a', 'postal_code' => '14089', 'city' => 'Berlin', 'district' => 'Gatow', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 170, 'street' => 'Bautzener Str 36', 'postal_code' => '10829', 'city' => 'Berlin', 'district' => 'Kreuzberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 171, 'street' => 'Kurfürstendamm. 46', 'postal_code' => '10785', 'city' => 'Berlin ', 'district' => 'Charlottenburg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 172, 'street' => 'Heerstraße  552', 'postal_code' => '1359', 'city' => 'Berlin', 'district' => 'Spandau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 173, 'street' => 'Trebbiner Str. 45903', 'postal_code' => '14547', 'city' => 'Beelitz', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 174, 'street' => 'Am Kühlungraben 4a', 'postal_code' => '14959', 'city' => 'Trebbin', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 175, 'street' => 'Marchwitzastr 29', 'postal_code' => '12681', 'city' => 'Marzahn', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 176, 'street' => 'Str. am Bahnhof 7', 'postal_code' => '14547', 'city' => 'Beelitz', 'district' => 'Heilstätten', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 177, 'street' => 'Halleschen Ufer 40', 'postal_code' => '10963', 'city' => 'Berlin', 'district' => 'Kreuzberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 178, 'street' => 'Karl-Marx- Str 169', 'postal_code' => '15713', 'city' => 'Königs Wusterhausen', 'district' => 'Niederlehme', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 179, 'street' => 'Am Ostbahnhof 9', 'postal_code' => '10243', 'city' => 'Berlin', 'district' => 'Friedrichshain', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 180, 'street' => 'Badstr 4', 'postal_code' => '13357', 'city' => 'Berlin', 'district' => 'Gesundbrunnen', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 181, 'street' => 'Pappelallee 47', 'postal_code' => '10437', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 182, 'street' => 'Turmstr. 60', 'postal_code' => '10551', 'city' => 'Berlin ', 'district' => 'Wedding', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 183, 'street' => 'In der Feldmark 3a', 'postal_code' => '14476', 'city' => 'Potsdam', 'district' => 'Golem', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 184, 'street' => 'Landsberger Allee 117', 'postal_code' => '10407', 'city' => 'Berlin', 'district' => 'Lichtenberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 185, 'street' => 'Hauptstr 45', 'postal_code' => '15741', 'city' => 'Bestensee', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 186, 'street' => 'Prenzlauer  Promenade  44', 'postal_code' => '13089', 'city' => 'Berlin', 'district' => 'Prenzlauer Berg ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 187, 'street' => 'Motzener Str. 36', 'postal_code' => '12277', 'city' => 'Berlin ', 'district' => 'Marienfelde', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 188, 'street' => 'Teilest 26', 'postal_code' => '12099', 'city' => 'Berlin ', 'district' => 'Tempelhof', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 189, 'street' => 'Kantstr 7', 'postal_code' => '10623', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 190, 'street' => 'Wilmersdorfer Straße 26', 'postal_code' => '10585', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 191, 'street' => 'Mohrenstr. 67', 'postal_code' => '10117', 'city' => 'Berlin', 'district' => 'Mitte', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 192, 'street' => 'Schloßstraße 136', 'postal_code' => '12163', 'city' => 'Berlin ', 'district' => 'Steglitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 193, 'street' => 'Innsbrucker Str 37', 'postal_code' => '10825', 'city' => 'Berlin', 'district' => 'Schöneberg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 194, 'street' => 'Niemetzstr 47', 'postal_code' => '12055', 'city' => 'Berlin', 'district' => 'Neukölln', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 195, 'street' => 'Rewestr. 1', 'postal_code' => '16515', 'city' => 'Oranienburg ', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 196, 'street' => 'Oscharfer Ring 10', 'postal_code' => '14979', 'city' => 'Großbeeren', 'district' => 'NULL', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 197, 'street' => 'Am Müggelpark 10', 'postal_code' => '15537', 'city' => 'Gosen', 'district' => 'Neu-Zittau', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 198, 'street' => 'Am Müggelpark 10', 'postal_code' => '15537', 'city' => 'Gosen ', 'district' => 'Burig ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 199, 'street' => 'Kurfürstendamm  231', 'postal_code' => '10719', 'city' => 'Berlin', 'district' => 'Charlottenburg', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 200, 'street' => 'Müllerstr 25', 'postal_code' => '13353', 'city' => 'Berlin', 'district' => 'Wedding ', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 201, 'street' => 'Tempelhofer Damm 191', 'postal_code' => '12099', 'city' => 'Berlin', 'district' => 'Tempelhof', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 202, 'street' => 'Schloßstraße 11', 'postal_code' => '12163', 'city' => 'Berlin ', 'district' => 'Steglitz', 'remark' => 'automatisch erzeugt']);
        ADDRESS::create(['id' => 203, 'street' => 'Altes Gaswerk Mariendorf 31', 'postal_code' => '12105', 'city' => 'Berlin', 'district' => 'Mariendorf', 'remark' => 'automatisch erzeugt']);
    }
}
